import type {
  AuthenticatorTransportFuture,
  CredentialDeviceType,
  Base64URLString,
} from "@simplewebauthn/server";

// ─── User ────────────────────────────────────────────────────────────────────

/**
 * Application user representation.
 * The `id` is an opaque, internal identifier (e.g. database primary key).
 */
export type PasskeyUser = {
  id: string;
  username: string;
};

// ─── Passkey credential ──────────────────────────────────────────────────────

/**
 * Stored WebAuthn credential.
 * Mirrors the fields recommended by the SimpleWebAuthn documentation.
 */
export type Passkey = {
  /** Base64URL-encoded credential ID. */
  id: Base64URLString;
  /** Raw public key bytes. */
  publicKey: Uint8Array;
  /** WebAuthn user ID (opaque, generated by SimpleWebAuthn). */
  webAuthnUserID: Base64URLString;
  /** Signature counter – used for replay-attack detection. */
  counter: number;
  /** `'singleDevice'` or `'multiDevice'`. */
  deviceType: CredentialDeviceType;
  /** Whether the credential has been backed up (e.g. synced passkey). */
  backedUp: boolean;
  /** Transport hints the browser can use to contact the authenticator. */
  transports?: AuthenticatorTransportFuture[];
};

// ─── Storage adapters ────────────────────────────────────────────────────────

/**
 * Persistence adapter for users and credentials.
 *
 * Implement this interface to plug in your own database
 * (Cloudflare D1, Prisma, Drizzle, etc.).
 */
export interface PasskeyStore {
  /** Look up a user by their username / email. */
  getUserByUsername(username: string): Promise<PasskeyUser | null>;

  /** Look up a user by their internal ID. */
  getUserById(userId: string): Promise<PasskeyUser | null>;

  /** Persist a brand-new user. */
  createUser(user: PasskeyUser): Promise<void>;

  /** Return every passkey credential belonging to a user. */
  getPasskeysByUser(userId: string): Promise<Passkey[]>;

  /**
   * Retrieve a single credential by its Base64URL credential ID.
   * Must also return the owning `userId` so the middleware can
   * identify who just authenticated.
   */
  getPasskeyById(
    credentialId: Base64URLString,
  ): Promise<(Passkey & { userId: string }) | null>;

  /** Store a new passkey credential for the given user. */
  savePasskey(userId: string, passkey: Passkey): Promise<void>;

  /** Update the signature counter after a successful authentication. */
  updatePasskeyCounter(
    credentialId: Base64URLString,
    newCounter: number,
  ): Promise<void>;
}

// ─── Challenge store ─────────────────────────────────────────────────────────

/**
 * Temporary storage for WebAuthn challenges.
 *
 * Challenges must survive between the "generate options" request and the
 * subsequent "verify" request – but should expire shortly after.
 */
export interface ChallengeStore {
  /** Save a challenge, optionally with a TTL. */
  set(key: string, challenge: string, ttlMs?: number): Promise<void>;

  /** Retrieve (and typically delete) a previously stored challenge. */
  get(key: string): Promise<string | null>;

  /** Explicitly remove a challenge. */
  delete(key: string): Promise<void>;
}

// ─── Middleware options ──────────────────────────────────────────────────────

export type PasskeyMiddlewareOptions = {
  /** Human-readable name for the Relying Party (shown in browser UI). */
  rpName: string;

  /**
   * Relying Party ID – typically your domain name (e.g. `"example.com"`).
   * `"localhost"` is fine during development.
   */
  rpID: string;

  /**
   * Allowed origin(s) for WebAuthn ceremonies.
   * Must match what the browser sends (e.g. `"https://example.com"`).
   * Pass an array to allow multiple origins.
   */
  origin: string | string[];

  /** Adapter that persists users and credentials. */
  store: PasskeyStore;

  /**
   * Adapter for temporary challenge storage.
   * When omitted the middleware falls back to a built-in
   * `InMemoryChallengeStore` (suitable for single-process dev servers).
   */
  challengeStore?: ChallengeStore;

  /**
   * URL path prefix for all four passkey endpoints.
   * @default "/passkey"
   */
  pathPrefix?: string;
};
